# Generated by Django 4.2.15 on 2024-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_alter_task_deadline_alter_taskevent_deadline'),
        ('users', '0002_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='tasker.task', verbose_name='задачи'),
        ),
    ]
