# Generated by Django 4.2.15 on 2024-09-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0009_alter_task_executor'),
        ('users', '0005_remove_user_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasker.task'),
        ),
    ]
