# Generated by Django 4.2.15 on 2024-09-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
    ]
