# Generated by Django 4.2.15 on 2024-09-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0011_remove_task_insert_insert_remove_task_update_update_and_more'),
        ('users', '0007_remove_user_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(related_name='users', to='tasker.task'),
        ),
    ]
