# Generated by Django 4.2.16 on 2024-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0012_alter_task_executors'),
        ('users', '0008_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='workers', to='tasker.task'),
        ),
    ]
