# Generated by Django 4.2.16 on 2024-09-26 09:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0013_remove_task_insert_insert_remove_task_update_update_and_more'),
        ('users', '0009_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='workers', to='tasker.task', verbose_name='Задачи'),
        ),
    ]
