# Generated by Django 4.2.15 on 2024-09-11 15:48

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0006_delete_aggregateevent'),
        ('tasker', '0002_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='update_update',
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, choices=[('purchase', 'Закупка'), ('spare parts', 'Запчасти'), ('modification', 'Модификация'), ('service', 'Обслуживание'), ('education', 'Обучение'), ('offer', 'Предложение'), ('development', 'Разработка')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='tag',
            field=models.CharField(blank=True, choices=[('purchase', 'Закупка'), ('spare parts', 'Запчасти'), ('modification', 'Модификация'), ('service', 'Обслуживание'), ('education', 'Обучение'), ('offer', 'Предложение'), ('development', 'Разработка')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasker.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in progress', 'В процессе'), ('closed', 'Закрыто'), ('delayed', 'Задержано')], max_length=15),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='tasker.task'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in progress', 'В процессе'), ('closed', 'Закрыто'), ('delayed', 'Задержано')], max_length=15),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tasker_taskevent" ("deadline", "executor_id", "id", "is_active", "is_important", "name", "notes", "parent_task_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "responsible_manager_id", "status", "tag", "updated_at") VALUES (NEW."deadline", NEW."executor_id", NEW."id", NEW."is_active", NEW."is_important", NEW."name", NEW."notes", NEW."parent_task_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority", NEW."responsible_manager_id", NEW."status", NEW."tag", NEW."updated_at"); RETURN NULL;', hash='dce79545d5176a956423341a1d0de8474cc594dc', operation='INSERT', pgid='pgtrigger_insert_insert_78725', table='tasker_task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "tasker_taskevent" ("deadline", "executor_id", "id", "is_active", "is_important", "name", "notes", "parent_task_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "responsible_manager_id", "status", "tag", "updated_at") VALUES (NEW."deadline", NEW."executor_id", NEW."id", NEW."is_active", NEW."is_important", NEW."name", NEW."notes", NEW."parent_task_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority", NEW."responsible_manager_id", NEW."status", NEW."tag", NEW."updated_at"); RETURN NULL;', hash='9978b2c81cf4bd72ff6cdf313a86e655fef04535', operation='UPDATE', pgid='pgtrigger_update_update_48fa8', table='tasker_task', when='AFTER')),
        ),
    ]
