# Generated by Django 4.2.15 on 2024-09-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_remove_task_insert_insert_remove_task_update_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
