# Generated by Django 4.2.15 on 2024-09-15 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasker', '0008_alter_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(blank=True, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='исполнители'),
        ),
    ]
