# Generated by Django 4.2.16 on 2024-09-26 09:14

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0012_alter_task_executors'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='task',
            name='update_update',
        ),
        migrations.RemoveField(
            model_name='taskevent',
            name='responsible_manager',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='срок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активная'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='примечание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in progress', 'В процессе'), ('closed', 'Закрыто'), ('delayed', 'Задержано')], max_length=15, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, choices=[('purchase', 'Закупка'), ('spare parts', 'Запчасти'), ('modification', 'Модификация'), ('service', 'Обслуживание'), ('education', 'Обучение'), ('offer', 'Предложение'), ('development', 'Разработка')], max_length=20, null=True, verbose_name='тэг'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='срок'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активная'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='примечание'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='priority',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in progress', 'В процессе'), ('closed', 'Закрыто'), ('delayed', 'Задержано')], max_length=15, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='tag',
            field=models.CharField(blank=True, choices=[('purchase', 'Закупка'), ('spare parts', 'Запчасти'), ('modification', 'Модификация'), ('service', 'Обслуживание'), ('education', 'Обучение'), ('offer', 'Предложение'), ('development', 'Разработка')], max_length=20, null=True, verbose_name='тэг'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tasker_taskevent" ("deadline", "id", "is_active", "name", "notes", "parent_task_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "status", "tag", "updated_at") VALUES (NEW."deadline", NEW."id", NEW."is_active", NEW."name", NEW."notes", NEW."parent_task_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority", NEW."status", NEW."tag", NEW."updated_at"); RETURN NULL;', hash='92b21cc24f3a8e01b9f7843d046a7e7d61b5b563', operation='INSERT', pgid='pgtrigger_insert_insert_78725', table='tasker_task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."deadline" IS DISTINCT FROM (NEW."deadline") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."is_active" IS DISTINCT FROM (NEW."is_active") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."notes" IS DISTINCT FROM (NEW."notes") OR OLD."parent_task_id" IS DISTINCT FROM (NEW."parent_task_id") OR OLD."priority" IS DISTINCT FROM (NEW."priority") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."tag" IS DISTINCT FROM (NEW."tag") OR OLD."updated_at" IS DISTINCT FROM (NEW."updated_at"))', func='INSERT INTO "tasker_taskevent" ("deadline", "id", "is_active", "name", "notes", "parent_task_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "status", "tag", "updated_at") VALUES (NEW."deadline", NEW."id", NEW."is_active", NEW."name", NEW."notes", NEW."parent_task_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority", NEW."status", NEW."tag", NEW."updated_at"); RETURN NULL;', hash='55ed8b6095aa2fb41c5ebdd7c4d2bd4cf73358cc', operation='UPDATE', pgid='pgtrigger_update_update_48fa8', table='tasker_task', when='AFTER')),
        ),
    ]
